require: rubocop-rails
AllCops:
  inherit_mode:
    merge:
      - Exclude

  NewCops: enable

  Exclude:
    - db/**
    - bin/**

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
