name: 'Ruby on Rails Ci'

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubunts-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@vs3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
